// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyUhTKNFFDmfUJkCrJ8v5656dd53Abt0Q',
    appId: '1:168767102842:web:a9fd5edf924814f0b3c0c3',
    messagingSenderId: '168767102842',
    projectId: 'didi-auth',
    authDomain: 'didi-auth.firebaseapp.com',
    storageBucket: 'didi-auth.appspot.com',
    measurementId: 'G-WYCWK3QJ96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaPCgsgBEA7F4YHSWd0k0Fkm155IxsX-A',
    appId: '1:168767102842:android:9e42c168dd109c28b3c0c3',
    messagingSenderId: '168767102842',
    projectId: 'didi-auth',
    storageBucket: 'didi-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAlDFSm9DJu7kZdQCNhbD-F2-XQaUtnYk',
    appId: '1:168767102842:ios:6eeac8915a59df20b3c0c3',
    messagingSenderId: '168767102842',
    projectId: 'didi-auth',
    storageBucket: 'didi-auth.appspot.com',
    iosBundleId: 'com.didicab.didiauth2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAlDFSm9DJu7kZdQCNhbD-F2-XQaUtnYk',
    appId: '1:168767102842:ios:6eeac8915a59df20b3c0c3',
    messagingSenderId: '168767102842',
    projectId: 'didi-auth',
    storageBucket: 'didi-auth.appspot.com',
    iosBundleId: 'com.didicab.didiauth2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyUhTKNFFDmfUJkCrJ8v5656dd53Abt0Q',
    appId: '1:168767102842:web:8b8fa518b38424aab3c0c3',
    messagingSenderId: '168767102842',
    projectId: 'didi-auth',
    authDomain: 'didi-auth.firebaseapp.com',
    storageBucket: 'didi-auth.appspot.com',
    measurementId: 'G-NRNDXZ5RYZ',
  );
}
